version: '3.8'
services:
  jenkins:
    build:
      context: .
      args:
        DOCKER_GID: 988
    user: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    container_name: jenkins-server
    restart: unless-stopped

volumes:
  jenkins_home:
