version: '3.8'
services:
  # Jenkins Controller Service
  jenkins:
    # Build the image from our custom Dockerfile in the current directory
    build: 
      context: .
    # CRITICAL FIX: Run as 'root' to guarantee permission to access /var/run/docker.sock.
    # NOTE: This is less secure than running as the 'jenkins' user, but necessary to overcome the persistent permission error.
    user: root 
    # Map container ports to host ports
    ports:
      - "8080:8080" # Jenkins web UI
      - "50000:50000" # Jenkins agent communication
    # Mount local directories for persistence and Docker access
    volumes:
      # Persistent storage for Jenkins data
      - jenkins_home:/var/jenkins_home
      # Mount the Docker socket for Jenkins to run Docker commands
      - /var/run/docker.sock:/var/run/docker.sock
    # Set necessary environment variables for Docker operations within Jenkins
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    container_name: jenkins-server
    restart: unless-stopped

volumes:
  jenkins_home:
