version: '3.8'
services:
  # Jenkins Controller Service
  jenkins:
    build: 
      context: .
    # Runs as 'root' to guarantee permission to access /var/run/docker.sock.
    user: root 
    # This port mapping requires 8080 to be free on the EC2 host.
    ports:
      - "8080:8080" 
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    container_name: jenkins-server
    restart: unless-stopped

volumes:
  jenkins_home:
