version: '3.8'
services:
  jenkins:
    # Use the official Jenkins LTS Docker image
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Persistent storage for Jenkins data
      - jenkins_home:/var/jenkins_home
      # Mount the Docker socket for Jenkins to run Docker commands
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      # ⚠️ IMPORTANT: Replace '999' with the GID you found above (e.g., 123)
      - DOCKER_GID=1001 
    container_name: jenkins-server
    restart: unless-stopped
    command: /bin/bash -c "groupadd -g $$DOCKER_GID docker && usermod -aG docker jenkins && /usr/local/bin/jenkins.sh"

volumes:
  jenkins_home:
