name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      # Uses GitHub Secrets for secure login
      uses: docker/login-action@v3
      with:
        username: syed048  # !!! REPLACE with your actual DockerHub username
        password: ${{ secrets.DOCKERHUB_TOKEN }} # This MUST be a GitHub Secret

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: syed048/node-ci-cd-app:latest, syed048/node-ci-cd-app:${{ github.sha }} # !!! REPLACE with your actual DockerHub username/repository name
        # Build context is the root directory, so the Dockerfile COPY command works relative to it
